elearn/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("newword.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

newword/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path("", views.home, name="home"),
  path("lesson_test/<int:lesson_number>", views.lesson_test, name="lesson_test"),
  path("grading/", views.grading, name="grading"),
  path("review/<int:test_id>", views.review, name="review"),
  path("history/", views.view_history, name="history"),
  path("admin_history/", views.view_history_admin, name="admin_history"),
  path("register/", views.register, name="register"),
  path("random_test/<int:quest_num>", views.random_test, name="random_test"),
]

newword/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Lesson(models.Model):
  number = models.IntegerField()
  def __str__(self):
      return f"Lesson {self.number}"

class Test(models.Model):
  test_time = models.DateTimeField(auto_now_add=True)
  score = models.IntegerField(null=True)
  user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="answers")
  lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, blank=True, null=True)
  num_of_quest = models.IntegerField(blank=True, null=True)
  def __str__(self):
    return f"Test {self.pk} {self.user}"

class NewWord(models.Model):
  word_type = [
    (1, "Noun"),
    (2, "Verb"),
    (3, "Adjective"),
    (4, "Adverb"),
    (5, "Phrasal verb/Preposition")
  ]
  word = models.CharField(max_length=100)
  wtype = models.IntegerField(choices=word_type, default=1)
  meaning = models.CharField(max_length=100)
  lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, blank=True, null=True, related_name="words")
  def __str__(self):
    return f"{self.word} in {self.lesson}" 

class Quest(models.Model):
  quest_type = [
    (1, "Word fill"),
    (2, "Type choose"),
    (3, "Word meaning")
  ]
  result_type = [
    (0, "False"),
    (1, "True")
  ]
  question = models.CharField(max_length=500)
  result = models.CharField(max_length=150)
  qtype = models.IntegerField(choices=quest_type, default=1)
  answer = models.CharField(max_length=150, blank=True, null=True)
  correct = models.IntegerField(choices=result_type, blank=True, null=True)
  test = models.ForeignKey(Test, on_delete=models.CASCADE, related_name="user_answers")
  def __str__(self):
    return f"Quest {self.question}"

newword/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

class CustomUserCreationForm(UserCreationForm):
  class Meta(UserCreationForm.Meta):
    fields = UserCreationForm.Meta.fields + ("email",)

newword/views.py
from hashlib import new
from django.contrib.auth import login
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required, user_passes_test
from .models import Test, Lesson, NewWord, Quest
import random
from django.core import serializers
from django.http import JsonResponse
from .forms import CustomUserCreationForm
from django.urls import reverse

# Create your views here.

@login_required
def home(request):
  lessons = Lesson.objects.all()
  context = {
    "lessons": lessons,
  }
  return render(request, "home.html", context)

@login_required
def lesson_test(request, lesson_number):
  newWords = list(NewWord.objects.filter(lesson__number=lesson_number))
  
  test = Test()
  test.user = request.user
  test.lesson = Lesson.objects.filter(number=lesson_number).first()
  test.num_of_quest = len(newWords)
  test.save()
  
  random.shuffle(newWords)
  questions = []
  for newWord in newWords:
    quest = Quest()
    quest_str, result = "", ""
    r = random.randint(1,3)
    if newWord.wtype == 5:
      r = 3
    if r == 1:
      quest_str = f"{newWord.meaning.capitalize()}({newWord.get_wtype_display().lower()}) in English."
      result = newWord.word
    elif r == 2:
      quest_str = f"{newWord.word.capitalize()}({newWord.meaning.lower()}) word type."
      result = str(newWord.wtype)
    elif r == 3:
      quest_str = f"{newWord.word.capitalize()}({newWord.get_wtype_display().lower()}) meaning."
      result = newWord.meaning
    quest.question = quest_str
    quest.qtype = r
    quest.test = test
    quest.result = result
    quest.save()
    questions.append(quest)
  request.session["questpks"] = [x.pk for x in questions]
  context = {
    "test": test,
    "questions": questions,
  }
  return render(request, "test.html", context)

@login_required
def grading(request):
  if request.is_ajax and request.method == "POST":
    answer = request.POST.getlist("ans[]")
    questpks = request.session["questpks"]
    for ind, pk in enumerate(questpks):
      quest = Quest.objects.get(pk=pk)
      quest.answer = answer[ind]
      quest.correct = 0
      if answer[ind].lower() == quest.result.lower():
        quest.correct = 1
      quest.save()
    test = quest.test
    test.score = Quest.objects.filter(test=test).filter(correct=1).count()
    test.save()
    ser_instance = serializers.serialize('json', [ test, ])
    return JsonResponse({"test": ser_instance}, status=200)
  return JsonResponse({"error": ""}, status=400)

@login_required
def review(request, test_id):
  wtype = {
    "1": "Noun",
    "2": "Verb",
    "3": "Adjective",
    "4": "Adverb"
  }
  test = Test.objects.get(pk=test_id)
  quests = Quest.objects.filter(test=test)
  for quest in quests:
    if quest.result in wtype.keys():
      quest.result = wtype[quest.result]
    if quest.answer in wtype.keys():
      quest.answer = wtype[quest.answer]
  context = {
    "test": test,
    "quests": quests,
    
  }
  return render(request, "review.html", context)

@login_required
def view_history(request):
  tests = Test.objects.filter(user=request.user)
  context = {
    "tests": tests,
  }
  return render(request, "history.html", context)

@user_passes_test(lambda u: u.is_superuser)
def view_history_admin(request):
  tests = Test.objects.all()
  context = {
    "tests": tests,
  }
  return render(request, "history.html", context)

def register(request):
  if request.method == "GET":
    form = CustomUserCreationForm()
    context = {
      "form": form,
    }
    return render(request, "register.html", context)
  elif request.method == "POST":
    form = CustomUserCreationForm(request.POST)
    if form.is_valid:
      user = form.save()
      login(request, user)
      return redirect(reverse("home"))
    else:
      return redirect(reverse("register"))

@login_required
def random_test(request, quest_num):
  test = Test()
  test.user = request.user
  test.num_of_quest = quest_num
  test.save()
  
  allWords = list(NewWord.objects.all())
  wordCount = len(allWords)
  newWordInds, newWords, questions = [], [], []
  index = 0
  while index < test.num_of_quest:
    r = random.randint(1, wordCount-1)
    if r not in newWordInds:
      newWordInds.append(r)
      index += 1
  for pk in newWordInds:
    newWords.append(allWords[pk])
  for newWord in newWords:
    quest = Quest()
    quest_str, result = "", ""
    r = random.randint(1,3)
    if newWord.wtype == 5:
      r = 3
    if r == 1:
      quest_str = f"{newWord.meaning.capitalize()}({newWord.get_wtype_display().lower()}) in English."
      result = newWord.word
    elif r == 2:
      quest_str = f"{newWord.word.capitalize()}({newWord.meaning.lower()}) word type."
      result = str(newWord.wtype)
    elif r == 3:
      quest_str = f"{newWord.word.capitalize()}({newWord.get_wtype_display().lower()}) meaning."
      result = newWord.meaning
    quest.question = quest_str
    quest.qtype = r
    quest.test = test
    quest.result = result
    quest.save()
    questions.append(quest)
  request.session["questpks"] = [x.pk for x in questions]
  context = {
    "test": test,
    "questions": questions,
  }
  return render(request, "test.html", context)

newword/templates/history.html
{% extends "base.html" %}

{% load static %}

{% block title %}
  History
{% endblock %}

{% block css %}
{% endblock %}

{% block content %}
  <h3>History</h3>
  <hr>
  <ol>
    {% for test in tests %}
    <li><a href="{% url 'review' test.pk %}"> {{ test.user }} test at {{ test.test_time }}</a></li>
    {% empty %}
    There are no tests here. 
    <a href="{% url 'home' %}">Lets do some test!</a>
    {% endfor %}
  </ol>
{% endblock %}

{% block js %}
{% endblock %}

newword/templates/home.html
{% extends "base.html" %}

{% load static %}

{% block title %}
  Home
{% endblock %}

{% block css %}
{% endblock %}

{% block content %}
  <div class="test row">
    <div class="col-md-6">
      <h3>Random Test</h3>
      <hr>
      <ul>
        <li>
          <a href="{% url 'random_test' 20 %}">20 questions test</a>
        </li>
        <li>
          <a href="{% url 'random_test' 40 %}">40 questions test</a>
        </li>
      </ul>
    </div>
    <div class="col-md-6">
      <h3>Lesson test</h3>
      <hr>
      <ul>
        {% for lesson in lessons %}
        <li><a href="{% url 'lesson_test' lesson.number %}">Lesson {{ lesson.number }} ({{ lesson.words.all.count }} new words)</a></li>
        {% empty %}
        There are 0 lesson now, sorry about that!
        {% endfor %}
      </ul>
    </div>
  </div>
{% endblock %}

{% block js %}
{% endblock %}

newword/templates/register.html
{% extends "base.html" %}

{% block title %}
  Register
{% endblock %}

{% block css %}
<style>
  span {
    display: none;
  }
  label {
    display: block;
  }
  main {
    display: flex;
    justify-content: center;
    /* align-content: center; */
    height: 400px;
  }

  form {
    align-self: center;
  }
</style>
{% endblock %}

{% block content %}
  <form method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Register">
    <a href="{% url 'login' %}">Login</a>
  </form>
{% endblock %}

newword/templates/review.html
{% extends "base.html" %}

{% load static %}

{% block title %}
  Review
{% endblock %}

{% block css %}
  <style>
    .correct-1 {
      color: green !important;
    }
    .correct-0 {
      color: red !important;
    }
  </style>
{% endblock %}

{% block content %}
<h3 class="d-inline"> Review {{ test.lesson }} </h3>|&nbsp;{{ test.test_time }} 
<p>Test score: {{ test.score }}/{{ test.num_of_quest }} </p>
<br>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Question</th>
      <th scope="col">Your answer</th>
      <th scope="col">Correct answer</th>
      <th scope="col">Result</th>
    </tr>
  </thead>
  <tbody>
    {% for quest in quests %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ quest.question }}</td>
      <td>{{ quest.answer }}</td>
      <td>{{ quest.result }}</td>
      <td  class="correct-{{ quest.correct }}">{{ quest.get_correct_display }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

{% block js %}
{% endblock %}

newword/templates/test.html
{% extends "base.html" %}

{% load static %}

{% block title %}
  Test
{% endblock %}

{% block css %}
{% endblock %}

{% block content %}
  <h3 class="d-inline">{{ test.lesson|default:"Random" }} </h3>|&nbsp;{{ test.test_time }}
  <hr>
  <form method="POST">
    {% csrf_token %}
  {% for quest in questions %}
  <div class="question mb-4">
    <p class="quest-content">
      {{ forloop.counter }}. {{ quest.question }}
    </p>
    {% if quest.qtype == 1 or quest.qtype == 3 %}
    <input type="text" name="ans[]" value="" autocomplete="off" autocorrect="off" >
    {% else %}
    <fieldset id="group{{ forloop.counter }}">
      <input type="radio" id="noun{{ forloop.counter }}" class="type-radio" data-radio="radio{{ forloop.counter }}" name="ans{{ forloop.counter }}" value="1">
      <label for="noun{{ forloop.counter }}">Noun</label><br>
      <input type="radio" id="verb{{ forloop.counter }}" class="type-radio" data-radio="radio{{ forloop.counter }}" name="ans{{ forloop.counter }}" value="2">
      <label for="verb{{ forloop.counter }}">Verb</label><br>
      <input type="radio" id="adjective{{ forloop.counter }}" class="type-radio" data-radio="radio{{ forloop.counter }}" name="ans{{ forloop.counter }}" value="3">
      <label for="adjective{{ forloop.counter }}">Adjective</label><br>
      <input type="radio" id="adverb{{ forloop.counter }}" class="type-radio" data-radio="radio{{ forloop.counter }}" name="ans{{ forloop.counter }}" value="4">
      <label for="adverb{{ forloop.counter }}">Adverb</label><br>
      <input type="hidden" id="val-radio{{ forloop.counter }}" value="" name="ans[]">
    </fieldset>
    {% endif %}
  </div>
  {% endfor %}
  <input type="submit" value="Submit" class="btn btn-primary">
  </form> 
{% endblock %}

{% block js %}
<script text="javascript">
  $(".type-radio").each(function() {
    $(this).click(function() {
      let name = $(this).data("radio");
      let val = $(this).val();
      console.log(val);
      $("#val-"+name).val(val);
      console.log("#val-"+name);
    })
  });

  $("form").submit(function(e) {
    e.preventDefault();
    let serializedData = $(this).serialize();
    $.ajax({
      type: "POST",
      url: "{% url 'grading' %}",
      data: serializedData,
      success: function (response) {
        var test = JSON.parse(response["test"]);
        console.log(test);
        var fields = test[0]["fields"];
        var pk = test[0]["pk"];
        alert(`Test Result: ${ fields["score"] }/${ fields["num_of_quest"] }`);
        location.href = `/review/${pk}` ;
      },
      error: function (response) {
        console.log("0");
      }
    });
  });
</script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    {% block title %}
    {% endblock %}
  </title>
  {% load static %}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <style>
    body {
      min-height: 100vh;
      display: flex;
      flex-direction: column;
    }
    footer {
      margin-top: auto;
      display: flex;
      justify-content: center;
      align-items: center;
      background-color: ghostwhite;
      height: 50px;
    }
    input {
      padding: 5px 7px;
    }
  </style>
  {% block css %}
  {% endblock %}  
</head>
<body>
  <!-- header -->
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'home' %}">New words Test</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link" id="nav-cart" href="{% url 'history' %}">History</a>
          {% if request.user.is_superuser %}
          <a class="nav-item nav-link" id="nav-cart" href="{% url 'admin_history' %}">Admin history</a>
          {% endif %}
          <a class="nav-item nav-link" id="nav-order" href="https://www.google.com.vn/">Help</a>
        </div>
        <div class="navbar-nav ml-auto">
          {% if user.is_anonymous %}
          <a class="nav-item nav-link nav-user">Hello, Anonymous user</a>
          <a class="nav-item nav-link nav-func" href="{% url 'login' %}">Login</a>
          {% else %}
          <a class="nav-item nav-link nav-user">Hello, {{ user }}</a>
          <a class="nav-item nav-link nav-func" href="{% url 'logout' %}">Logout</a>
          {% endif %}
        </div>
      </div>
    </nav>
  </header>

  <main class="container">
    {% block content %}
    {% endblock %}
  </main>

  <!-- footer -->
  <footer>
    Made by Ghost.2021
  </footer>

  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <!-- <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script> -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <!-- myscript -->
  
  {% block js %}
  {% endblock %}
</body>
</html>